version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/cruddb
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      